### ISSUE TITLE
Error in extract_concepts_from_ontology.py

### ISSUE THREAD

**Issue by ulissesbcorrea** [SIREN-DST/Ontology-Enrichment#1]
Trying to run  **"extract_concepts_from_ontology.py**" raises an error

```
Traceback (most recent call last):
  File "extract_concepts_from_ontology.py", line 54, in <module>
    concepts = list(set(extract_concepts_from_ontologies(ontologies)))
  File "extract_concepts_from_ontology.py", line 49, in extract_concepts_from_ontologies
    concepts = [split_by_camel_case(term) for term in Ontology(ontology).terms.keys()]
AttributeError: 'function' object has no attribute 'keys'
```

**Comment by Remorax** [comment]
Hi,

Thank you for raising this issue, and apologies for the delay in response. This piece of code should work for earlier versions of pronto. I have just rechecked for `pronto==0.12.2` and it works fine for me. Could you try and install this version?
